#!/usr/bin/env python
import argparse
import sys
import models
import heapq
from collections import namedtuple

parser = argparse.ArgumentParser(description='Simple cur_phrase based decoder.')
parser.add_argument('-i', '--input', dest='input', default='data/input', help='File containing sentences to translate (default=data/input)')
parser.add_argument('-t', '--translation-model', dest='tm', default='data/tm', help='File containing translation model (default=data/tm)')
parser.add_argument('-s', '--stack-size', dest='s', default=1, type=int, help='Maximum stack size (default=1)')
parser.add_argument('-n', '--num_sentences', dest='num_sents', default=sys.maxint, type=int, help='Number of sentences to decode (default=no limit)')
parser.add_argument('-l', '--language-model', dest='lm', default='data/lm', help='File containing ARPA-format language model (default=data/lm)')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', default=False,  help='Verbose mode (default=off)')
opts = parser.parse_args()

tm = models.TM(opts.tm, sys.maxint)
lm = models.LM(opts.lm)
sys.stderr.write('Decoding %s...\n' % (opts.input,))
input_sents = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]

hypothesis = namedtuple('hypothesis', 'logprob, lm_state, predecessor, phrase')
phrase = namedtuple("phrase", "english, logprob")
for f in input_sents:
    # The following code implements a DP monotone decoding
    # algorithm (one that doesn't permute the target phrases).
    # Hence all hypotheses in stacks[i] represent translations of 
    # the first i words of the input sentence.
    # HINT: Generalize this so that stacks[i] contains translations
    # of any i words (remember to keep track of which words those
    # are, and to estimate future costs)
    initial_hypothesis = hypothesis(0.0, lm.begin(), None, None)

    stacks = [{} for _ in f] + [{}]
    stacks[0][lm.begin()] = initial_hypothesis
    for i, stack in enumerate(stacks[:-1]):
        # extend the top s hypotheses in the current stack
        for h in heapq.nlargest(opts.s, stack.itervalues(), key=lambda h: h.logprob): # prune
            for j in xrange(i+1,len(f)+1):
                if f[i:j] in tm:
                    for cur_phrase in tm[f[i:j]]:
                        logprob = h.logprob + cur_phrase.logprob
                        lm_state = h.lm_state
                        for word in cur_phrase.english.split():
                            (lm_state, word_logprob) = lm.score(lm_state, word)
                            logprob += word_logprob
                        logprob += lm.end(lm_state) if j == len(f) else 0.0
                        new_hypothesis = hypothesis(logprob, lm_state, h, cur_phrase)
                        if lm_state not in stacks[j] or stacks[j][lm_state].logprob < logprob: # second case is recombination
                            stacks[j][lm_state] = new_hypothesis 
                        # consider next cur_phrase to account for reordering
                        for k in xrange(j+1,len(f)+1):
                            if f[j:k] in tm:
                                #order_logprob = logprob
                                #order_lm_state = lm_state
                                for next_phrase in tm[f[j:k]]:
                                    #order_logprob += next_phrase.logprob
                                    reorder_logprob = h.logprob + cur_phrase.logprob + next_phrase.logprob
                                    reorder_lm_state = h.lm_state
                                    for word in next_phrase.english.split():
                                        #(order_lm_state, word_logprob) = lm.score(order_lm_state, word)
                                        #order_logprob += word_logprob
                                        (reorder_lm_state, reorder_word_logprob) = lm.score(reorder_lm_state, word)
                                        reorder_logprob += reorder_word_logprob
                                    for word in cur_phrase.english.split():
                                        (reorder_lm_state, reorder_word_logprob) = lm.score(reorder_lm_state, word)
                                        reorder_logprob += reorder_word_logprob
                                    #order_logprob += lm.end(order_lm_state) if k == len(f) else 0.0
                                    reorder_logprob += lm.end(reorder_lm_state) if k == len(f) else 0.0
                                    ## push two new hypothesis to the stack
                                    #new_hypothesis = hypothesis(logprob, lm_state, h, cur_phrase)
                                    #if lm_state not in stacks[j] or stacks[j][lm_state].logprob < logprob:
                                    #    stacks[j][lm_state] = new_hypothesis 
                                    two_phrase = phrase(next_phrase.english+' '+cur_phrase.english, cur_phrase.logprob+next_phrase.logprob)
                                    new_reorder_hypothesis = hypothesis(reorder_logprob, reorder_lm_state, h, two_phrase)
                                    if reorder_lm_state not in stacks[k] or stacks[k][reorder_lm_state].logprob < reorder_logprob:
                                        stacks[k][reorder_lm_state] = new_reorder_hypothesis 

    # find best translation by looking at the best scoring hypothesis
    # on the last stack
    winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
    def extract_english_recursive(h):
        return '' if h.predecessor is None else '%s%s ' % (extract_english_recursive(h.predecessor), h.phrase.english)
    print extract_english_recursive(winner)

    if opts.verbose:
        def extract_tm_logprob(h):
            return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
        tm_logprob = extract_tm_logprob(winner)
        sys.stderr.write('LM = %f, TM = %f, Total = %f\n' % 
            (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
